config/routes.rb
Rails.application.routes.draw do
  resources :spaces do
    resources :bookings, only: [:new, :create, :update, :edit]
  end
  resources :bookings, only: [:index, :show]
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :space
  validates :start_date, presence: true, if: :overlap?
  validates :end_date, presence: true, if: :overlap?
  validates :status, presence: true
  validates :cost, presence: true

  # Valdiation that dates fit
  def overlap?
    if self.space.start_date.nil? && self.space.end_date.nil?
      if end_date < start_date
        overlap_error
      else
        return true
      end
    else
      range = Range.new start_date, end_date
      if range.end.nil? || range.begin.nil?
        overlap_error
      else
        overlaps = Space.where(id: self.space).in_range(range)
        overlap_error if overlaps.empty?
      end
    end
  end

  def overlap_error
    errors.add(:overlap_error, 'Your request is outside of the offered booking times!')
  end
end

app/models/space.rb
class Space < ApplicationRecord
  belongs_to :user
  has_many :bookings
  mount_uploader :photo, PhotoUploader
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  validates :address, presence: true
  validate :time_order?
  validates :price, presence: true
  validates :size, presence: true
  validates :photo, presence: true

  def time_order?
    if start_date.nil? && end_date.nil?
      return true
    else
      time_error if end_date < start_date
    end
  end

  def time_error
    errors.add(:time_error, 'Times aren\'t added correctly!')
  end

  scope :in_range, -> range {
  where('(start_date <= ? and ? <= ? and end_date >= ?)',range.first, range.first, range.last, range.last)
  }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :spaces
  has_many :bookings
  has_many :bookings_as_owner, through: :spaces, source: :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #Before every method can be called a log in is necessary (can be deactivated with: skip_before_action :authenticate_user!, only:NAME_OF_METHOD )
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  def configure_permitted_parameters
    # First and Last name field for Log-in
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

   private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = policy_scope(Booking).order(created_at: :desc)
    @spaces = current_user.bookings_as_owner
    @user = current_user
  end

  def show
    @booking = Booking.find(params[:id])
    @markers =
      [{
        lat: @booking.space.latitude,
        lng: @booking.space.longitude,
      }]
    authorize @booking
  end

  def new
    @space = Space.find(params[:space_id])
    @booking = Booking.new(space: @space)
    authorize @booking
    respond_to do |format|
      format.js { render layout: false, content_type: 'text/javascript' }
      format.html
    end
  end

  def create
    @space = Space.find(params[:space_id])
    @booking = Booking.new(booking_params)
    @booking.space = @space
    @booking.user = current_user
    authorize @booking
    if @booking.end_date && @booking.start_date
      @total_cost = @space.price * (@booking.end_date - @booking.start_date)
      @booking.cost = @total_cost
      if @booking.save
        redirect_to bookings_path
      else
        render :new
      end
    else
      render :new
    end
  end

  def update
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.status = params[:status]
    @booking.save
    redirect_to bookings_path
  end

  def edit
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :cost, :status, :space, :user)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/spaces_controller.rb
class SpacesController < ApplicationController
  #for more info about this go to application_controller or sources from yesterday!
  #if a method is written here you DO NOT NEED TO LOG IN to call it!
  skip_before_action :authenticate_user!, only: [:index, :show]
  def index
    if params[:query].present?
      @spaces = policy_scope(Space).where.not(latitude: nil, longitude: nil, user: current_user).where("address ILIKE ?", "%#{params[:query]}%")
      @markers = @spaces.map do |space|
      {
        lat: space.latitude,
        lng: space.longitude,
      }
      end
    else
      @spaces = policy_scope(Space).where.not(latitude: nil, longitude: nil, user: current_user)
      @markers = @spaces.map do |space|
      {
        lat: space.latitude,
        lng: space.longitude,
      }
      end
    end
  end

  def show
    @space = Space.find(params[:id])
    @markers =
      [{
        lat: @space.latitude,
        lng: @space.longitude,
      }]
    authorize @space
  end


  def new
    @space = Space.new
    authorize @space
  end

  def create
    @space = Space.new(space_params)
    @space.user = current_user
    authorize @space
    if @space.save
      redirect_to space_path(@space)
    else
      render :new
    end
  end

  def destroy
    @space = Space.find(params[:id])
    @space.user = current_user
    authorize @space
    @space.destroy
    redirect_to bookings_path
  end

  def edit
    @space = Space.find(params[:id])
    @space.user = current_user
    authorize @space
  end

  def update
    @space = Space.find(params[:id])
    @space.user = current_user
    authorize @space
    if @space.update(space_params)
      redirect_to space_path(@space)
    else
      render :new
    end
  end

  private

  def space_params
    params.require(:space).permit(:address, :start_date, :end_date, :price, :size, :photo, :photo_cache)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_current_bookings.html.erb
<% count = 0 %>

<% @bookings.each do |booking| %>
  <% if booking.start_date <= Date.parse(Time.now.strftime('%Y/%m/%d')) && booking.end_date >= Date.parse(Time.now.strftime('%Y/%m/%d')) %>
    <% if booking.status == "confirmed" %>
      <% count =+ 1 %>
      <div class="card">
        <div class="card-header bg-success">
          <h6 class="my-0" style= "height: 16px;"> Status: <%=booking.status%></h6>
        </div>
        <div class="card-body d-flex justify-content-between">
          <div>
            <h5 class="card-title">Address: <%=booking.space.address%></h5>
            <p class="card-text">From <%=booking.start_date%>  To  <%=booking.end_date%></p>
            <p class="card-text"> Size: <%=booking.space.size%> m²</p>
           </div>
          <div>
            <p class="card-text">Total: <%= booking.cost %> €</p>
            <%= link_to "Go to this booking", booking_path(booking), class: "button" %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
<% end %>
<% if count == 0 %>
  <div class="container">
    <div class="container" style="justify-content: center;">
      <p>You don't have any confirmed bookings</p>
      <%= link_to "Book a space", spaces_path, class: "button" %>
    </div>
  </div>
<% end %>

app/views/bookings/_display_bookings.html.erb
    <div class="card">
      <% if booking.status == "confirmed" %>
        <div class="card-header bg-success">
          <h6 class="my-0" style= "height: 16px;"> Status: <%=booking.status%></h6>
        </div>
      <% end %>
      <% if booking.status == "pending" %>
        <div class="card-header bg-warning">
          <h6 class="my-0" style= "height: 16px;"> Status: <%=booking.status%></h6>
        </div>
      <% end %>
      <% if booking.status == "reject" %>
        <div class="card-header bg-danger">
          <h6 class="my-0" style= "height: 16px;"> Status: <%=booking.status%></h6>
        </div>
      <% end %>
      <div class="card-body d-flex justify-content-between">
       <div>
        <h5 class="card-title">Address: <%=booking.space.address%></h5>
        <p class="card-text">From <%=booking.start_date%>  To  <%=booking.end_date%></p>
        <p class="card-text"> Size: <%=booking.space.size%> m²</p>
       </div>
      <div>
        <p class="card-text">Total: <%= booking.cost %> €</p>
        <%= link_to "Go to this booking", booking_path(booking), class: "button" %>
      </div>
      </div>
    </div>

app/views/bookings/_future_bookings.html.erb
<% count = 0 %>

<% bookings.each do |booking| %>
  <% count =+ 1 %>
  <% if booking.start_date > Date.parse(Time.now.strftime('%Y/%m/%d'))%>
    <div class="card">
      <% case booking.status
       when "confirmed"
          headerClass = "bg-success"
        when "pending"
          headerClass = "bg-warning"
        when "reject"
          headerClass = "bg-danger"
        else
          headerClass = "bg-warning"
        end %>
      <div class="card-header <%= headerClass %>" >
        <h6 class="my-0" style= "height: 16px;"> Status: <%=booking.status%></h6>
        </div>
      <div class="card-body d-flex justify-content-between">
       <div>
        <h5 class="card-title">Address: <%=booking.space.address%></h5>
        <p class="card-text">From <%=booking.start_date%>  To  <%=booking.end_date%></p>
        <p class="card-text"> Size: <%=booking.space.size%> m²</p>
       </div>
      <div>
        <p class="card-text">Total: <%= booking.cost %> €</p>
        <%= link_to "Go to this booking", booking_path(booking), class: "button" %>
      </div>
      </div>
    </div>
  <% end %>
<% end %>
<% if count == 0 %>
  <div class="container">
    <div class="container" style="justify-content: center;">
      <p>You don't have any future bookings</p>
      <%= link_to "Book a space", spaces_path, class: "button" %>
    </div>
  </div>
<% end %>

app/views/bookings/_my_spaces.html.erb
<% spaces = user.spaces  %>
<% if spaces.empty? %>
  <div class="container">
    <div class="container" style="justify-content: center;">
      <p>You have not uploaded any space</p>
      <%= link_to "New space", new_space_path, class: "button" %>
    </div>
  </div>
<% else %>
  <div class="container pl-0">
    <% user.spaces.each do  |space| %>
      <div class="container pt-2 mb-3 pb-4" style="background-color: white;">
        <div class="card mb-1 mt-3" style="flex-direction: row; padding: 10px;  border:none; box-shadow: 0 0 0;" >
          <%  if space.photo %>
           <%= cl_image_tag(space.photo, width: 160, height: 160, crop: :fill) %>
          <% end  %>

          <div class="card-body " >
            <h5 class="card-title" style="margin: 0; padding: 0;"><%= space.address %></h5>
            <h5 class="card-text" style="margin: 0; padding: 0;">Price: <%= space.price %> €</h5>
            <h5 class="card-text pb-2" style="margin: 0; padding: 0;">Size: <%= space.size %> m²</h5>
            <% if space.bookings.empty? %>
            <%= link_to "Edit", edit_space_path(space), class: "button h5" %>
            <% end %>
          </div>
        </div>
        <div class="container">
          <% space.bookings.each do |booking| %>
            <div class="card" style="padding: 0px; box-shadow: 0 0 0;">
              <% case booking.status
                when "confirmed" || "accepted"
                  headerClass = "bg-success"
                when "pending"
                  headerClass = "bg-warning"
                when "reject"
                  headerClass = "bg-danger"
                else
                  headerClass = "bg-warning"
              end %>
              <div class="card-header <%= headerClass %>" style="padding: 4px;">
                <h6 class="my-0" style= "height: 16px;"> Status: <%=booking.status%></h6>
              </div>
              <div class="card-body d-flex justify-content-between">
                <div>
                <h5 class="card-title">Address: <%=booking.space.address%></h5>
                <h5 class="card-text">From <%=booking.start_date%>  To  <%=booking.end_date%></h5>
                <h5 class="card-text"> Size: <%=booking.space.size%> m²</h5>
                  <h5>Total:  <%= booking.cost %> €</h5>
                </div>
                <div>
                  <div class="row pt-4">
                    <% if booking.status == "pending" || booking.status == "" %>
                    <%= link_to "Accept", space_booking_path(booking.space, booking, status:"confirmed"), method: :patch, class: "button bg-success" %>
                    <%= link_to "Reject", space_booking_path(booking.space, booking, status:"rejected"), method: :patch, class: "button bg-warning mr-2 ml-2" %>
                    <% end %>
                    <%= link_to "Go to this booking", booking_path(booking), class: "button" %>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/bookings/_past_bookings.html.erb
<% count = 0 %>
<% @bookings.each do |booking| %>
  <% if booking.end_date < Date.parse(Time.now.strftime('%Y/%m/%d'))%>
    <% if booking.status == "confirmed" %>
    <% count =+ 1 %>
      <div class="card">
        <div class="card-header bg-success">
          <h6 class="my-0" style= "height: 16px;"> Status: <%=booking.status%></h6>
        </div>
        <div class="card-body d-flex justify-content-between">
          <div>
            <h5 class="card-title">Address: <%=booking.space.address%></h5>
            <p class="card-text">From <%=booking.start_date%>  To  <%=booking.end_date%></p>
            <p class="card-text"> Size: <%=booking.space.size%> m²</p>
           </div>
          <div>
            <p class="card-text">Total: <%= booking.cost %> €</p>
            <%= link_to "Go to this booking", booking_path(booking), class: "button" %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
<% end %>
<% if count == 0 %>
  <div class="container">
    <div class="container" style="justify-content: center;">
      <p>You don't have confirmed past bookings</p>
      <%= link_to "Book a space", spaces_path, class: "button" %>
    </div>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<h1>Bookings#edit</h1>
<p>Find me in app/views/bookings/edit.html.erb</p>

app/views/bookings/index.html.erb
<div class="container mt-2" >
  <ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item">
      <a class="nav-link " id="future-tab" data-toggle="tab" href="#future" role="tab" aria-controls="future" aria-selected="true">My future bookings</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" id="current-tab" data-toggle="tab" href="#current" role="tab" aria-controls="current" aria-selected="false">My current bookings</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" id="past-tab" data-toggle="tab" href="#past" role="tab" aria-controls="past" aria-selected="false">My booking history</a>
    </li>
    <li class="nav-item">
      <a class="nav-link active" id="manage_my_spaces-tab" data-toggle="tab" href="#manage_my_spaces" role="tab" aria-controls="manage_my_spaces" aria-selected="false">Manage my parking spaces</a>
    </li>
  </ul>
  <div class="tab-content" id="myTabContent">
    <div class="tab-pane fade " id="future" role="tabpanel" aria-labelledby="future-tab">
      <%= render "future_bookings", bookings: @bookings  %>
    </div>
    <div class="tab-pane fade" id="current" role="tabpanel" aria-labelledby="current-tab">
      <%= render "current_bookings", bookings: @bookings  %>
    </div>
    <div class="tab-pane fade" id="past" role="tabpanel" aria-labelledby="past-tab">
      <%= render "past_bookings", bookings: @bookings  %>
    </div>
    <div class="tab-pane fade show active" id="manage_my_spaces" role="tabpanel" aria-labelledby="manage_my_spaces-tab">
        <div>
          <%= render "my_spaces", user: @user %>
        </div>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>My booking details</title>
</head>
<body>
  <div class="container ">
    <div class = "my-3 py-2" ><h2 class="font-weight-bold text-center">Your Booking on <%=@booking.start_date.to_date%></h2></div>

    <div class="d-flex">

      <div class="card bg-dark text-white mx-3 p-0" style="width:60%;height:65vh;border-style: none;">
        <div id="map" style="width: 100%; height: 100%;"
         data-markers="<%= @markers.to_json %>"
         data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
        <div class="card-img-overlay d-flex justify-content-between" style=" position: absolute; top: 63%;background-color: rgba(180,180,180,.5); height: 37%;">
          <div style="color: black;height: -moz-fit-content;">
            <div class="d-flex">
              <i class="large material-icons" style="color: #02CCBA; margin-right: 8px;">location_on</i>
              <h5 class="card-title"><%=@booking.space.address%></h5>
            </div>
            <p class="card-text">Starts: <%=@booking.start_date%></p>
            <p class="card-text">End: <%=@booking.end_date%></p>
            <p class="card-text">Contact: <%=@booking.user.email%></p>
          </div>
          <div>
            <h5 class="card-text" style="position: relative; top: 0;color: black;height: -moz-fit-content;;width:max-content;">Total:<%=@booking.cost%> Euro</h5>
          </div>
        </div>
      </div>

  <div class="card" style="width: 40%;height: 65vh;">
  <div class="card-body" style = "text-align:center;">
    <h4 class = "mb-4" style="width:max-content;margin-left: 30px"> You rent a space from</h4>
    <img class="rounded-circle alone mb-4" src="https://avatars0.githubusercontent.com/u/50922534?v=4" width="85">
    <h5 class="card-title"><%=@booking.space.user.email%></h5>
    <div class="d-flex" >
        <i class="large material-icons" style="color: #02CCBA;margin-left: 48px;">pets</i>
        <p class="card-text">on Parking Dog since: </p>
    </div>
       <p> <%=@booking.space.user.created_at.to_date%></p>
    <div style="margin-top: 16px;">
      <%= link_to "Go Back to my dashboard", bookings_path, class: "button"%>
    </div>
  </div>
 </div>
</div>
</div>
</body>
</html>

app/views/pages/home.html.erb
<%= content_for(:navbar_class, "navbar_home") %>

<%= cl_image_tag("map-dark-berlin_en6ctp.png", class: "banner-img") %>
<div class="banner">
  <div class="banner-content text-center">
    <h1>Parking dog</h1>
    <h3 class="mb-3" style="color: rgba(245,245,245,.9);">Rent private parking spaces in the city</h3>
    <div class="banner-btn">
      <%= link_to "Find a Space", spaces_path, class: "button"  %>
      <%= link_to "Rent out your space", new_space_path, class: "button"  %>
    </div>
  </div>
</div>

<div class="container search-bar col-6">
    <div class="search-bar">
        <%= form_tag spaces_path, method: :get, class: "d-flex search-bar" do %>
        <%= text_field_tag :query,
            params[:query],
            class: "form-control bar",
            placeholder: "Find a parking space" %>
         <%= submit_tag "Search",class: "button ml-2" %>
        <% end %>
    </div>
</div>

<div class="container">
  <div class="container home-outer-container">
    <h3 class="text-center pb-3">Get the best parking space in the city at the right price</h3>
    <div class="container home-inner-container">
      <div class="home-card">
        <img class="card-img-top" src="https://images.unsplash.com/photo-1559564484-e48b3e040ff4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=900&q=80" alt="Card image cap">
        <div>
          <h5 class="card-header">Search for the best locations</h5>
          <p class="card-text">
            Find your perfect parking location in the city.
          </p>
        </div>
      </div>
      <div class="home-card" style="width: 18rem;">
        <img class="card-img-top" src="https://images.unsplash.com/photo-1555582467-bc8792666232?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1351&q=80" alt="Card image cap">
        <div>
          <p class="card-header">Rent from private owners</p>
          <p class="card-text">
            Parking in the street is not cool. Go for a private parking space.
          </p>
        </div>
      </div>
      <div class="home-card" style="width: 18rem;">
        <img class="card-img-top" src="https://images.unsplash.com/photo-1506784365847-bbad939e9335?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=900&q=80" alt="Card image cap">
        <div>
          <p class="card-header">Flexible dates</p>
          <p class="card-text">Choose only the days that you need a parking space</p>
        </div>
      </div>
    </div>
    <div class="text-center">
      <%= link_to "Book a space", root_path, class: "button"  %>
    </div>
    <hr>
  </div>

</div>



<div class="container">
  <div class="container home-outer-container">
    <h3 class="text-center pb-3">Rent out your parking space and make money on the side</h3>
    <div class="container home-inner-container">
      <div class="home-card" style="width: 18rem;">
        <img class="card-img-top" src="https://images.unsplash.com/photo-1542353436-312f0e1f67ff?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=854&q=80" alt="Card image cap">
        <div>
          <p class="card-header">Make extra money</p>
          <p class="card-text">
            If you have a space available why not rent it and make extra money!
          </p>
        </div>
      </div>
      <div class="home-card" style="width: 18rem;">
        <img class="card-img-top" src="https://images.unsplash.com/photo-1498887960847-2a5e46312788?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80" alt="Card image cap">
        <div>
          <p class="card-header">Rent from private clients</p>
          <p class="card-text">
            Rent to people signed up in our platform
          </p>
        </div>
      </div>
      <div class="home-card" style="width: 18rem;">
        <img class="card-img-top" src= "https://images.unsplash.com/photo-1519669072050-a51e9a929312?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=740&q=80">
        <div>
          <p class="card-header">Flexible dates</p>
          <p class="card-text">
            Block the dates that you need your parking space
          </p>
        </div>
      </div>
    </div>
    <div class="text-center">
      <%= link_to "Rent out your space", new_space_path, class: "button"  %>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer",>
  <%= link_to "About us", root_path, class: "footer-link" %>
  <div class="footer-copyright mt-2" style="font-size: 12px;">
    ©Parking dog <i class="fas fa-dog" ></i>
  </div>
</div>

app/views/spaces/destroy.html.erb
<h1>Spaces#destroy</h1>
<p>Find me in app/views/spaces/destroy.html.erb</p>

app/views/spaces/index.html.erb
<div class="container" >

  <div class="container d-flex justify-content-between">

    <div class="index-cards mr-5" >
       <div class="search-bar m-0 w-10">
        <%= form_tag spaces_path, method: :get, class: "d-flex search-bar" do %>
        <%= text_field_tag :query,
            params[:query],
            class: "form-control ",
            placeholder: "Find a parking space" %>
         <%= submit_tag "Search",class: "button ml-2" %>
        <% end %>
       </div>
       <div class="cards-container overflow-auto" style="margin-bottom: 50px;">
         <% @spaces.each do  |space| %>
          <%= link_to space_path(space) do %>
           <div class="card mb-1 justify-content-between card-link"
           style="width: 400px; flex-direction: row; padding: 10px;" >
             <%  if space.photo %>
             <%= cl_image_tag(space.photo, width: 160, height: 160, crop: :fill) %>
             <% end %>

            <div class="card-body my-3 mr-0" >
              <h5 id = "title_index" class="card-title link" style="margin: 0; padding: 0; color: #02CCBA;"><%= space.address %></h5>
              <p class="card-text" style="margin: 0; padding: 0; color: black;">Price: <%= space.price %> euro</p>
              <p class="card-text mb-2" style="margin: 0; padding: 0; color: black;">Size: <%= space.size %></p>
            </div>
           </div>
           <% end %>
         <% end %>
      </div>
  </div>

    <div class="map flex-grow-1" style="margin-top: 56px; margin-bottom: 30px;">
      <% if @spaces.count <= 2 %>
      <div id="map" style="width: 100%; height: 60vh; min-width: 500px; position: sticky; top: 0;"
         data-markers="<%= @markers.to_json %>"
         data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
      <% else %>
      <div id="map" style="width: 100%; height: 100vh; min-width: 500px; position: sticky; top: 0;"
         data-markers="<%= @markers.to_json %>"
         data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
      <% end %>
    </div>

  </div>
</div>

app/views/spaces/show.html.erb
<div class="container pt-4">
  <h1 class="text-center pb-3"><%= @space.address %></h1>
  <div class="mx-auto" style="object-fit:cover; width: 100%;
    height: 250px;">
    <div id="map" style="width: 100%; height: 100%;"
         data-markers="<%= @markers.to_json %>"
         data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
    <div class="space-card row py-4 px-3">
      <%  if @space.photo.filename %>
        <%= cl_image_tag(@space.photo, width: 250, height: 200, crop: :fill) %>
      <% else %>
        <%= image_tag("https://images.unsplash.com/photo-1470224114660-3f6686c562eb?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=400&q=80", style: "object-fit:cover; height: 250px; width: 250px") %>
      <% end  %>
      <div class="card flex-grow-1">
        <div class="card-body d-flex justify-content-between p-2">
           <div>
              <div class="d-flex">
                <i class="large material-icons" style="color: #02CCBA; margin-right: 8px;">location_on</i>
                <h3 class="card-title"><%= @space.address%></h3>
              </div>
            <%if @space.start_date.nil? && @space.end_date.nil? %>
               <p class="card-text" style="font-family: Muli">Available</p>
            <% else %>
               <p class="card-text" style="font-family: Muli">Available from <%= @space.start_date%> to <%= @space.end_date%></p>
            <% end %>
            <p class="card-text"style="font-family: Muli">Size: <%= @space.size%></p>
          </div>
          <div class="flex-column justify-content-between">
            <h3 class="card-text">Price/Day: <%= @space.price %>Euro</h3>
            <% unless @space.user == current_user %>
              <div style="margin-top: 40px;margin-left: 32px;">
                <%= link_to "Book now", new_space_booking_path(@space), class: "button"%>
              </div>
            <% end %>
            <% if @space.user == current_user && @space.bookings.empty? %>
              <div style="margin-top: 40px;margin-left: 30px;">
                <%= link_to "Edit", edit_space_path(@space), class: "button"%>
                <%= link_to "Delete", space_path(@space),
                  method: :delete,
                  data: { confirm: "Are you sure?" }, class: "button" %>

              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
</div>